export  const Add_Task='Add_Task'
export  const Delete_Task='Delete_Task'
export  const Done_Task='Done_Task'
export  const Edit_Task='Edit_Task'
export  const FiltreDone_Task='FiltreDone_Task'
export  const FiltreUnDone_Task='FiltreUnDone_Task'